<a href="https://colab.research.google.com/github/geoafrikana/mit-deeplearning/blob/main/Py4DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/Churn_Modelling (1).csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.shape

(10000, 14)

In [6]:
len(df.columns)

14

In [14]:
X= df.iloc[:,3:-1].values
y= df.iloc[:,-1].values

In [15]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [16]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [17]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [18]:
labelencoder = LabelEncoder()
X[:, 2] = labelencoder.fit_transform(X[:,2])

In [19]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [20]:
from sklearn.compose import ColumnTransformer

In [22]:
ct = ColumnTransformer([('ohe', OneHotEncoder(), [1])], remainder= 'passthrough')

In [30]:
X = np.array(ct.fit_transform(X), dtype=np.str)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [31]:
X = X[:,1:]

In [32]:
X

array([['0.0', '0.0', '619', ..., '1', '1', '101348.88'],
       ['0.0', '1.0', '608', ..., '0', '1', '112542.58'],
       ['0.0', '0.0', '502', ..., '1', '0', '113931.57'],
       ...,
       ['0.0', '0.0', '709', ..., '0', '1', '42085.58'],
       ['1.0', '0.0', '772', ..., '1', '0', '92888.52'],
       ['0.0', '0.0', '792', ..., '1', '0', '38190.78']], dtype='<U9')

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

In [37]:
from sklearn.preprocessing import StandardScaler

In [39]:
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [42]:
from keras.models import Sequential

In [43]:
from keras.layers import Dense

In [44]:
classifier = Sequential()

In [45]:
classifier.add(Dense(units=6, activation='relu', kernel_initializer='uniform', input_dim=11))

In [46]:
classifier.add(Dense(units=6, activation='relu', kernel_initializer='uniform'))

In [47]:
classifier.add(Dense(units=1, activation='sigmoid', kernel_initializer='uniform'))

In [49]:
classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [50]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
800/800 [==============================] - 3s 2ms/step - loss: 0.4933 - accuracy: 0.7959
Epoch 2/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4286 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4228 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4185 - accuracy: 0.8192
Epoch 5/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4162 - accuracy: 0.8269
Epoch 6/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4145 - accuracy: 0.8298
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4130 - accuracy: 0.8310
Epoch 8/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4115 - accuracy: 0.8320
Epoch 9/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4104 - accuracy: 0.8317
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4097 - accura

In [51]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred>0.5)

In [52]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [54]:
confusion_matrix(y_test, y_pred)

array([[1544,   51],
       [ 258,  147]])

In [55]:
accuracy_score(y_test, y_pred)

0.8455

In [57]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dropout, Dense

In [58]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 1s 0us/step


In [63]:
X_train = X_train.reshape((X_train.shape[0]), X_train.shape[1], X_train.shape[2], 1)
X_test = X_test.reshape((X_test.shape[0]), X_test.shape[1], X_test.shape[2], 1)

In [65]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [66]:
X_train = X_train/255
X_test = X_test/255

In [67]:
model = Sequential()

In [68]:
model.add(Conv2D(32,(3,3), activation='relu', input_shape=(28,28,1)))

In [69]:
model.add(MaxPool2D(2,2))

In [70]:
model.add(Flatten())

In [71]:
model.add(Dense(100,activation='relu'))

In [72]:
model.add(Dense(10, activation='softmax'))

In [73]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [74]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 59s 31ms/step - loss: 0.1600 - accuracy: 0.9527
Epoch 2/10
1875/1875 [==============================] - 43s 23ms/step - loss: 0.0568 - accuracy: 0.9826
Epoch 3/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0361 - accuracy: 0.9886
Epoch 4/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0245 - accuracy: 0.9923
Epoch 5/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0175 - accuracy: 0.9942
Epoch 6/10
1875/1875 [==============================] - 55s 29ms/step - loss: 0.0121 - accuracy: 0.9962
Epoch 7/10
1875/1875 [==============================] - 43s 23ms/step - loss: 0.0089 - accuracy: 0.9972
Epoch 8/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0072 - accuracy: 0.9975
Epoch 9/10
1875/1875 [==============================] - 38s 20ms/step - loss: 0.0060 - accuracy: 0.9979
Epoch 10/10
1875/1875 [==============================] - 37s 20m

In [75]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 3s 8ms/step - loss: 0.0582 - accuracy: 0.9858


[0.05818773806095123, 0.98580002784729]